// ==UserScript==
// @name         Malwarebytes
// @namespace    Malwarebytes.com
// @run-at document-start
// @version      0.2
// @description  Checks for malware on websites
// @author       Malwarebytes.com
// @match        *://*.newsmax.com/*
// @match        *://*.oann.com/*
// @match        *://*.albusinessdaily.com/*
// @match        *://*.auburntimes.com/*
// @match        *://*.baldwintimes.com/*
// @match        *://*.decaturtimes.com/*
// @match        *://*.ecalabamanews.com/*
// @match        *://*.gadsdentoday.com/*
// @match        *://*.huntsvilleleader.com/*
// @match        *://*.jeffersonreporter.com/*
// @match        *://*.mobilecourant.com/*
// @match        *://*.nealabamanews.com/*
// @match        *://*.northbirminghamtimes.com/*
// @match        *://*.nwalabamanews.com/*
// @match        *://*.riverregiontimes.com/*
// @match        *://*.shoalstoday.com/*
// @match        *://*.southalabamatimes.com/*
// @match        *://*.southbirminghamtimes.com/*
// @match        *://*.tuscaloosaleader.com/*
// @match        *://*.wcalabamanews.com/*
// @match        *://*.wiregrasstimes.com/*
// @match        *://*.yellowhammertimes.com/*
// @match        *://*.akbusinessdaily.com/*
// @match        *://*.interioralaskanews.com/*
// @match        *://*.lastfrontiernews.com/*
// @match        *://*.matsutimes.com/*
// @match        *://*.northalaskanews.com/*
// @match        *://*.scalaskanews.com/*
// @match        *://*.sealaskanews.com/*
// @match        *://*.swalaskanews.com/*
// @match        *://*.angolabusinessdaily.com/*
// @match        *://*.azbusinessdaily.com/*
// @match        *://*.azcatholictribune.com/*
// @match        *://*.coconinonews.com/*
// @match        *://*.eastarizonanews.com/*
// @match        *://*.glendalesun.com/*
// @match        *://*.grandcanyontimes.com/*
// @match        *://*.mohavetoday.com/*
// @match        *://*.nevalleytimes.com/*
// @match        *://*.northpimanews.com/*
// @match        *://*.nwvalleytimes.com/*
// @match        *://*.peoriasun.com/*
// @match        *://*.phxreporter.com/*
// @match        *://*.pinaltoday.com/*
// @match        *://*.searizonanews.com/*
// @match        *://*.sevalleytimes.com/*
// @match        *://*.southpimanews.com/*
// @match        *://*.surprisejournal.com/*
// @match        *://*.swarizonanews.com/*
// @match        *://*.swvalleytimes.com/*
// @match        *://*.tucsonstandard.com/*
// @match        *://*.yavapainews.com/*
// @match        *://*.arbusinessdaily.com/*
// @match        *://*.bentontimes.com/*
// @match        *://*.eastlittlerocktimes.com/*
// @match        *://*.fayettevillestandard.com/*
// @match        *://*.fortsmithtimes.com/*
// @match        *://*.hotspringstimes.com/*
// @match        *://*.jonesborotimes.com/*
// @match        *://*.lowedeltanews.com/*
// @match        *://*.naturalstatenews.com/*
// @match        *://*.ncarkansasnews.com/*
// @match        *://*.northlittlerocktimes.com/*
// @match        *://*.nwarkansasnews.com/*
// @match        *://*.pulaskitimes.com/*
// @match        *://*.swarkansastimes.com/*
// @match        *://*.upperdeltanews.com/*
// @match        *://*.balkanbusinesswire.com/*
// @match        *://*.antelopevalleytoday.com/*
// @match        *://*.cabusinessdaily.com/*
// @match        *://*.calaverasguide.com/*
// @match        *://*.centralalamedanews.com/*
// @match        *://*.centraloctimes.com/*
// @match        *://*.chicotimes.com/*
// @match        *://*.coachellatoday.com/*
// @match        *://*.eastalamedanews.com/*
// @match        *://*.eastcontracostanews.com/*
// @match        *://*.eastsandiegonews.com/*
// @match        *://*.eastsbvtimes.com/*
// @match        *://*.eastsfvtoday.com/*
// @match        *://*.eastsierranews.com/*
// @match        *://*.eastventuranews.com/*
// @match        *://*.fresnoleader.com/*
// @match        *://*.goldcountrytoday.com/*
// @match        *://*.goldenstatetoday.com/*
// @match        *://*.imperialcanews.com/*
// @match        *://*.kerncountytimes.com/*
// @match        *://*.kingscountytimes.com/*
// @match        *://*.laharbornews.com/*
// @match        *://*.laketahoesun.com/*
// @match        *://*.laxleader.com/*
// @match        *://*.marinleader.com/*
// @match        *://*.mercedtimes.com/*
// @match        *://*.montereytimes.com/*
// @match        *://*.necalinews.com/*
// @match        *://*.nesacramentonews.com/*
// @match        *://*.norcalrecord.com/*
// @match        *://*.northcoastcanews.com/*
// @match        *://*.northinlandnews.com/*
// @match        *://*.northoctimes.com/*
// @match        *://*.northsactoday.com/*
// @match        *://*.northsfvtoday.com/*
// @match        *://*.northsgvnews.com/*
// @match        *://*.nwlatimes.com/*
// @match        *://*.nwriversidenews.com/*
// @match        *://*.oaklandrecord.com/*
// @match        *://*.pomonavalleynews.com/*
// @match        *://*.reddingtoday.com/*
// @match        *://*.redwoodempirenews.com/*
// @match        *://*.sacramentostandard.com/*
// @match        *://*.sandiegorecord.com/*
// @match        *://*./*
// @match        *://*.sanfransun.com/*
// @match        *://*.sanjoaquintimes.com/*
// @match        *://*.sanjosestandard.com/*
// @match        *://*.sanmateosun.com/*
// @match        *://*.santaclaratoday.com/*
// @match        *://*.santacruzstandard.com/*
// @match        *://*.selatimes.com/*
// @match        *://*.sfvtoday.com/*
// @match        *://*.sgvstandard.com/*
// @match        *://*.sloreporter.com/*
// @match        *://*.socalrecord.com/*
// @match        *://*.solanosun.com/*
// @match        *://*.southalamedanews.com/*
// @match        *://*.southbayleader.com/*
// @match        *://*.southbaysdnews.com/*
// @match        *://*.southoctimes.com/*
// @match        *://*.southsactoday.com/*
// @match        *://*.southsfbaynews.com/*
// @match        *://*.southsfvtoday.com/*
// @match        *://*.southsgvnews.com/*
// @match        *://*.stanislausnews.com/*
// @match        *://*.swriversidenews.com/*
// @match        *://*.tularetimes.com/*
// @match        *://*.verdugosnews.com/*
// @match        *://*.victorvalleytimes.com/*
// @match        *://*.westcontracostanews.com/*
// @match        *://*.westeldoradonews.com/*
// @match        *://*.westlatimes.com/*
// @match        *://*.westoctimes.com/*
// @match        *://*.westsbvtimes.com/*
// @match        *://*.westsfvtoday.com/*
// @match        *://*.westsgvnews.com/*
// @match        *://*.westventuranews.com/*
// @match        *://*.winecountrytimes.com/*
// @match        *://*.yubasuttertimes.com/*
// @match        *://*.torontobusinessdaily.com/*
// @match        *://*.adamscountytimes.com/*
// @match        *://*.boulderleader.com/*
// @match        *://*.centennialstatenews.com/*
// @match        *://*.centralcoloradonews.com/*
// @match        *://*.cobusinessdaily.com/*
// @match        *://*.denvercitywire.com/*
// @match        *://*.eastarapahoenews.com/*
// @match        *://*.grandjunctiontimes.com/*
// @match        *://*.larimernews.com/*
// @match        *://*.necoloradonews.com/*
// @match        *://*.northjeffconews.com/*
// @match        *://*.secoloradonews.com/*
// @match        *://*.sedenvernews.com/*
// @match        *://*.southjeffconews.com/*
// @match        *://*.springstimes.com/*
// @match        *://*.swcoloradonews.com/*
// @match        *://*.westarapahoenews.com/*
// @match        *://*.cistranfinance.com/*
// @match        *://*.bridgeporttimes.com/*
// @match        *://*.constitutionstatenews.com/*
// @match        *://*.ctbusinessdaily.com/*
// @match        *://*.hartfordreporter.com/*
// @match        *://*.housatonicvalleynews.com/*
// @match        *://*.litchfieldhillstoday.com/*
// @match        *://*.naugatucktimes.com/*
// @match        *://*.neconnnews.com/*
// @match        *://*.nwconnnews.com/*
// @match        *://*.scconnnews.com/*
// @match        *://*.seconnnews.com/*
// @match        *://*.swconnnews.com/*
// @match        *://*.debusinessdaily.com/*
// @match        *://*.firststatetimes.com/*
// @match        *://*.kentcountytoday.com/*
// @match        *://*.northnewcastlenews.com/*
// @match        *://*.southnewcastlenews.com/*
// @match        *://*.sussexreview.com/*
// @match        *://*.apopkatimes.com/*
// @match        *://*.baldwinparktoday.com/*
// @match        *://*.brevardsun.com/*
// @match        *://*.centralbrowardnews.com/*
// @match        *://*.claycotimes.com/*
// @match        *://*.collegeparktoday.com/*
// @match        *://*.doctorphillipstoday.com/*
// @match        *://*.duvaltimes.com/*
// @match        *://*.easthillsboroughnews.com/*
// @match        *://*.eastpanhandlenews.com/*
// @match        *://*.eastvolusianews.com/*
// @match        *://*.emeraldcoasttimes.com/*
// @match        *://*.flarecord.com/*
// @match        *://*.flbusinessdaily.com/*
// @match        *://*.flcatholictribune.com/*
// @match        *://*.goldenrodnews.com/*
// @match        *://*.gothatoday.com/*
// @match        *://*.hernandoreporter.com/*
// @match        *://*.hunterscreeknews.com/*
// @match        *://*.indiantownguide.com/*
// @match        *://*.keywestreporter.com/*
// @match        *://*.lakebuenavistanews.com/*
// @match        *://*.lakebutlernews.com/*
// @match        *://*.lakehartnews.com/*
// @match        *://*.lakenonatoday.com/*
// @match        *://*.leetoday.com/*
// @match        *://*.maitlandtoday.com/*
// @match        *://*.manateereview.com/*
// @match        *://*.miamicourant.com/*
// @match        *://*.naplesstandard.com/*
// @match        *://*.naturecoasttimes.com/*
// @match        *://*.ncfloridanews.com/*
// @match        *://*.nefloridanews.com/*
// @match        *://*.northbrowardnews.com/*
// @match        *://*.northlaketimes.com/*
// @match        *://*.northmianews.com/*
// @match        *://*.northorlandonews.com/*
// @match        *://*.northpalmbeachtoday.com/*
// @match        *://*.northpanhandlenews.com/*
// @match        *://*.northpinellasnews.com/*
// @match        *://*.ocalastandard.com/*
// @match        *://*.ocoeetoday.com/*
// @match        *://*.okeechobeetimes.com/*
// @match        *://*.orlandostandard.com/*
// @match        *://*.palmcoasttimes.com/*
// @match        *://*.panamacityreporter.com/*
// @match        *://*.pascoreporter.com/*
// @match        *://*.pensacolatimes.com/*
// @match        *://*.pinellastimes.com/*
// @match        *://*.polktimes.com/*
// @match        *://*.sarasotareview.com/*
// @match        *://*.southbrowardnews.com/*
// @match        *://*.southlaketoday.com/*
// @match        *://*.southmianews.com/*
// @match        *://*.southorlandonews.com/*
// @match        *://*.southpalmbeachtoday.com/*
// @match        *://*.southpinellastimes.com/*
// @match        *://*.stpetestandard.com/*
// @match        *://*.sumtertimes.com/*
// @match        *://*.sunshinesentinel.com/*
// @match        *://*.tallahasseesun.com/*
// @match        *://*.tamparepublic.com/*
// @match        *://*.treasurecoastsun.com/*
// @match        *://*.wadeviewparknews.com/*
// @match        *://*.westflnews.com/*
// @match        *://*.westhillsboroughnews.com/*
// @match        *://*.westvolusianews.com/*
// @match        *://*.windermeretoday.com/*
// @match        *://*.albanystandard.com/*
// @match        *://*.athensreporter.com/*
// @match        *://*.atlstandard.com/*
// @match        *://*.centralgeorgianews.com/*
// @match        *://*.coastalganews.com/*
// @match        *://*.cobbreporter.com/*
// @match        *://*.dekalbganews.com/*
// @match        *://*.ecgeorgianews.com/*
// @match        *://*.gabusinessdaily.com/*
// @match        *://*.georgiamountainnews.com/*
// @match        *://*.macontimes.com/*
// @match        *://*.ncgeorgianews.com/*
// @match        *://*.neatlantanews.com/*
// @match        *://*.northfultontoday.com/*
// @match        *://*.northgwinnettnews.com/*
// @match        *://*.nwatlantanews.com/*
// @match        *://*.nwgeorgianews.com/*
// @match        *://*.peachtreetimes.com/*
// @match        *://*.romereporter.com/*
// @match        *://*.savannahstandard.com/*
// @match        *://*.seatlantanews.com/*
// @match        *://*.segeorgianews.com/*
// @match        *://*.southatlantanews.com/*
// @match        *://*.southfultontoday.com/*
// @match        *://*.southgeorgiatimes.com/*
// @match        *://*.southgwinnettnews.com/*
// @match        *://*.swgeorgianews.com/*
// @match        *://*.warnerrobinstoday.com/*
// @match        *://*.wcgeorgianews.com/*
// @match        *://*.westatlantanews.com/*
// @match        *://*.gulfnewsjournal.com/*
// @match        *://*.alohastatenews.com/*
// @match        *://*.bigislandtimes.com/*
// @match        *://*.hibusinessdaily.com/*
// @match        *://*.honolulureporter.com/*
// @match        *://*.kauaisun.com/*
// @match        *://*.mauireporter.com/*
// @match        *://*.adareporter.com/*
// @match        *://*.boisecitywire.com/*
// @match        *://*.cdareporter.com/*
// @match        *://*.centralidahotimes.com/*
// @match        *://*.eastidahotimes.com/*
// @match        *://*.gemstatewire.com/*
// @match        *://*.idbusinessdaily.com/*
// @match        *://*.magicvalleytimes.com/*
// @match        *://*.northidahotimes.com/*
// @match        *://*.pocatellotimes.com/*
// @match        *://*.treasurevalleytimes.com/*
// @match        *://*.carbondalereporter.com/*
// @match        *://*.chambanasun.com/*
// @match        *://*.chicagocitywire.com/*
// @match        *://*.cookcountyrecord.com/*
// @match        *://*.cretereview.com/*
// @match        *://*.dekalbtimes.com/*
// @match        *://*.dupagepolicyjournal.com/*
// @match        *://*.eastcentralreporter.com/*
// @match        *://*.egyptianreview.com/*
// @match        *://*.galesburgreporter.com/*
// @match        *://*.grundyreporter.com/*
// @match        *://*.ilbusinessdaily.com/*
// @match        *://*.illinoisvalleytimes.com/*
// @match        *://*.kanecountyreporter.com/*
// @match        *://*.kankakeetimes.com/*
// @match        *://*.kendallcountytimes.com/*
// @match        *://*.laharpeguide.com/*
// @match        *://*.lakecountygazette.com/*
// @match        *://*.lynwoodtimes.com/*
// @match        *://*.maconreporter.com/*
// @match        *://*.madisoncountyguide.com/*
// @match        *://*.madisonrecord.com/*
// @match        *://*.mcleancountytimes.com/*
// @match        *://*.metroeastsun.com/*
// @match        *://*.northcooknews.com/*
// @match        *://*.northegyptnews.com/*
// @match        *://*.nwillinoisnews.com/*
// @match        *://*.peoriastandard.com/*
// @match        *://*.prairiestatewire.com/*
// @match        *://*.quincyreporter.com/*
// @match        *://*.rockfordsun.com/*
// @match        *://*.rockislandtoday.com/*
// @match        *://*.salemnewswire.com/*
// @match        *://*.sangamonsun.com/*
// @match        *://*.seillinoisnews.com/*
// @match        *://*.silnews.com/*
// @match        *://*.southcentralreporter.com/*
// @match        *://*.southcooknews.com/*
// @match        *://*.swillinoisnews.com/*
// @match        *://*.westcentralreporter.com/*
// @match        *://*.westcooknews.com/*
// @match        *://*.willcountygazette.com/*
// @match        *://*.andersonreporter.com/*
// @match        *://*.bloomingtonleader.com/*
// @match        *://*.columbusstandard.com/*
// @match        *://*.eastindynews.com/*
// @match        *://*.ecindiananews.com/*
// @match        *://*.elkharttimes.com/*
// @match        *://*.ftwaynetimes.com/*
// @match        *://*.hancockguide.com/*
// @match        *://*.hoosierstatetoday.com/*
// @match        *://*.indianabusinessdaily.com/*
// @match        *://*.indystandard.com/*
// @match        *://*.kentuckianatimes.com/*
// @match        *://*.kokomostandard.com/*
// @match        *://*.lafayettetimes.com/*
// @match        *://*.monontoday.com/*
// @match        *://*.munciereporter.com/*
// @match        *://*.ncindiananews.com/*
// @match        *://*.neindiananews.com/*
// @match        *://*.northindynews.com/*
// @match        *://*.seindiananews.com/*
// @match        *://*.southbendtimes.com/*
// @match        *://*.southernindianatoday.com/*
// @match        *://*.southindynews.com/*
// @match        *://*.swindiananews.com/*
// @match        *://*.theregionnews.com/*
// @match        *://*.wcindiananews.com/*
// @match        *://*.westindynews.com/*
// @match        *://*.adairmadisonnews.com/*
// @match        *://*.amestoday.com/*
// @match        *://*.ankenyguide.com/*
// @match        *://*.boonecountyguide.com/*
// @match        *://*.boyervalleynews.com/*
// @match        *://*.buchanancountynews.com/*
// @match        *://*.carrollcoguide.com/*
// @match        *://*.cedarfallsguide.com/*
// @match        *://*.cedarrapidstoday.com/*
// @match        *://*.centraliowatimes.com/*
// @match        *://*.clarkeunionnews.com/*
// @match        *://*.clintonreview.com/*
// @match        *://*.clivenews.com/*
// @match        *://*.crawfordcountytimes.com/*
// @match        *://*.dallascountyreview.com/*
// @match        *://*.delawarecoguide.com/*
// @match        *://*.desmoinesguide.com/*
// @match        *://*.desmoinessun.com/*
// @match        *://*.dewittreview.com/*
// @match        *://*.dubuquecoguide.com/*
// @match        *://*.dubuquetimes.com/*
// @match        *://*.eciowanews.com/*
// @match        *://*.elkhornguide.com/*
// @match        *://*.englishvalleyguide.com/*
// @match        *://*.fairfieldreview.com/*
// @match        *://*.floydvalleyguide.com/*
// @match        *://*.greenecountyguide.com/*
// @match        *://*.grimesjournal.com/*
// @match        *://*.grundyguide.com/*
// @match        *://*.guthriecountyguide.com/*
// @match        *://*.hawkeyereporter.com/*
// @match        *://*.humboldtreview.com/*
// @match        *://*.iabusinessdaily.com/*
// @match        *://*.idasacguide.com/*
// @match        *://*.indianolaguide.com/*
// @match        *://*.iowacitytoday.com/*
// @match        *://*.iowaregionalguide.com/*
// @match        *://*.jacksoncoguide.com/*
// @match        *://*.jaspercountyguide.com/*
// @match        *://*.johnstontimes.com/*
// @match        *://*.jonescountynews.com/*
// @match        *://*.mahaskaguide.com/*
// @match        *://*.marioncountyguide.com/*
// @match        *://*.marshallguide.com/*
// @match        *://*.millsfremontnews.com/*
// @match        *://*.montgomeryadamsnews.com/*
// @match        *://*.mtpleasantguide.com/*
// @match        *://*.neiowanews.com/*
// @match        *://*.northdsmnews.com/*
// @match        *://*.northiowareporter.com/*
// @match        *://*.norwalktimes.com/*
// @match        *://*.nwiowanews.com/*
// @match        *://*.ottumwaguide.com/*
// @match        *://*.pagetaylornews.com/*
// @match        *://*.poweshiekguide.com/*
// @match        *://*.ringgolddecaturnews.com/*
// @match        *://*.riverbendtimes.com/*
// @match        *://*.seiowanews.com/*
// @match        *://*.shelbycountytimes.com/*
// @match        *://*.siouxcitytimes.com/*
// @match        *://*.southdsmnews.com/*
// @match        *://*.southiowanews.com/*
// @match        *://*.swiowatimes.com/*
// @match        *://*.tamaguide.com/*
// @match        *://*.urbandaletimes.com/*
// @match        *://*.warrencountynews.com/*
// @match        *://*.washingtoncoguide.com/*
// @match        *://*.waterlooreview.com/*
// @match        *://*.waterlootimes.com/*
// @match        *://*.waukeetimes.com/*
// @match        *://*.wciowanews.com/*
// @match        *://*.westdesmoinesguide.com/*
// @match        *://*.westdsmnews.com/*
// @match        *://*.wiltonreview.com/*
// @match        *://*.wrightcountyguide.com/*
// @match        *://*.ashlandreview.com/*
// @match        *://*.eastwichitatimes.com/*
// @match        *://*.eckansasnews.com/*
// @match        *://*.galvaguide.com/*
// @match        *://*.glenelderguide.com/*
// @match        *://*.holyroodguide.com/*
// @match        *://*.hutchtoday.com/*
// @match        *://*.jocotoday.com/*
// @match        *://*.ksbusinessdaily.com/*
// @match        *://*.lawrencereporter.com/*
// @match        *://*.linncountyguide.com/*
// @match        *://*.littleappletimes.com/*
// @match        *://*.miltonvaleguide.com/*
// @match        *://*.moundridgeguide.com/*
// @match        *://*.nckansasnews.com/*
// @match        *://*.nekansasnews.com/*
// @match        *://*.northwichitanews.com/*
// @match        *://*.nwkansasnews.com/*
// @match        *://*.sckansasnews.com/*
// @match        *://*.sekansasnews.com/*
// @match        *://*.southwichitanews.com/*
// @match        *://*.sunflowerstatenews.com/*
// @match        *://*.swkansasnews.com/*
// @match        *://*.topekasun.com/*
// @match        *://*.wamegoguide.com/*
// @match        *://*.wichitastandard.com/*
// @match        *://*.wilsonguide.com/*
// @match        *://*.wyandottetimes.com/*
// @match        *://*.bluegrasstimes.com/*
// @match        *://*.bowlinggreentoday.com/*
// @match        *://*.eastkentuckytimes.com/*
// @match        *://*.eastlouisvillenews.com/*
// @match        *://*.eastpennyroyalnews.com/*
// @match        *://*.elizabethtowntimes.com/*
// @match        *://*.hopkinsvilletimes.com/*
// @match        *://*.jacksonpurchasenews.com/*
// @match        *://*.kybusinessdaily.com/*
// @match        *://*.louisvillecitywire.com/*
// @match        *://*.nckentuckynews.com/*
// @match        *://*.nekentuckynews.com/*
// @match        *://*.northbluegrassnews.com/*
// @match        *://*.northkentuckynews.com/*
// @match        *://*.nwkentuckynews.com/*
// @match        *://*.sebluegrassnews.com/*
// @match        *://*.sekentuckynews.com/*
// @match        *://*.swbluegrassnews.com/*
// @match        *://*.westpennyroyalnews.com/*
// @match        *://*.batonrougereporter.com/*
// @match        *://*.centrallouisiananews.com/*
// @match        *://*.floridaparishnews.com/*
// @match        *://*.houmathibodauxnews.com/*
// @match        *://*.labusinessdaily.com/*
// @match        *://*.lafayettereporter.com/*
// @match        *://*.louisianarecord.com/*
// @match        *://*.nelouisiananews.com/*
// @match        *://*.nolareporter.com/*
// @match        *://*.northacadiananews.com/*
// @match        *://*.northshorelanews.com/*
// @match        *://*.nwlouisiananews.com/*
// @match        *://*.pelicanstatenews.com/*
// @match        *://*.riverparishnews.com/*
// @match        *://*.shreveportreporter.com/*
// @match        *://*.southlouisiananews.com/*
// @match        *://*.swlouisiananews.com/*
// @match        *://*.westbanklanews.com/*
// @match        *://*.maghrebnewswire.com/*
// @match        *://*.aroostooknews.com/*
// @match        *://*.downeasttimes.com/*
// @match        *://*.grayguide.com/*
// @match        *://*.lewistontimes.com/*
// @match        *://*.mainebusinessdaily.com/*
// @match        *://*.mainehighlandsnews.com/*
// @match        *://*.mainelakesnews.com/*
// @match        *://*.midcoasttoday.com/*
// @match        *://*.oxfordmetoday.com/*
// @match        *://*.pinestatenews.com/*
// @match        *://*.portlandmainenews.com/*
// @match        *://*.rivervalleytoday.com/*
// @match        *://*.sacoriverguide.com/*
// @match        *://*.southmainenews.com/*
// @match        *://*.unitymaineguide.com/*
// @match        *://*.annearundeltoday.com/*
// @match        *://*.baltimorecitywire.com/*
// @match        *://*.harfordnews.com/*
// @match        *://*.howardconews.com/*
// @match        *://*.mdbusinessdaily.com/*
// @match        *://*.mdstatewire.com/*
// @match        *://*.montgomerymdnews.com/*
// @match        *://*.northbaltimorejournal.com/*
// @match        *://*.baystatenews.com/*
// @match        *://*.beantowntimes.com/*
// @match        *://*.bristolreporter.com/*
// @match        *://*.capecodledger.com/*
// @match        *://*.mabusinessdaily.com/*
// @match        *://*.merrimackvalleynews.com/*
// @match        *://*.metrowesttimes.com/*
// @match        *://*.midmassnews.com/*
// @match        *://*.ncmassnews.com/*
// @match        *://*.norfolkreporter.com/*
// @match        *://*.northbostonnews.com/*
// @match        *://*.plymouthreporter.com/*
// @match        *://*.springfieldrecord.com/*
// @match        *://*.westmassnews.com/*
// @match        *://*.mexicobusinessdaily.com/*
// @match        *://*.annarbortimes.com/*
// @match        *://*.baragaguide.com/*
// @match        *://*.battlecreektimes.com/*
// @match        *://*.branchguide.com/*
// @match        *://*.detroitcitywire.com/*
// @match        *://*.downrivertoday.com/*
// @match        *://*.easternwaynetoday.com/*
// @match        *://*.eastmichigannews.com/*
// @match        *://*.geneseenews.com/*
// @match        *://*.grandrapidsreporter.com/*
// @match        *://*.greatlakeswire.com/*
// @match        *://*.hollandreporter.com/*
// @match        *://*.kalamazootimes.com/*
// @match        *://*.lansingreporter.com/*
// @match        *://*.lansingsun.com/*
// @match        *://*.livingstontoday.com/*
// @match        *://*.macombtoday.com/*
// @match        *://*.mibusinessdaily.com/*
// @match        *://*.micapitolnews.com/*
// @match        *://*.micatholictribune.com/*
// @match        *://*.monroereview.com/*
// @match        *://*.munisingguide.com/*
// @match        *://*.muskegonsun.com/*
// @match        *://*.northkentnews.com/*
// @match        *://*.northmichigannews.com/*
// @match        *://*.novitimes.com/*
// @match        *://*.nwwaynenews.com/*
// @match        *://*.ontonagonguide.com/*
// @match        *://*.pontiactimes.com/*
// @match        *://*.segrandrapids.com/*
// @match        *://*.seoaklandnews.com/*
// @match        *://*.shelbyreview.com/*
// @match        *://*.shiawasseetimes.com/*
// @match        *://*.southkentnews.com/*
// @match        *://*.southmichigannews.com/*
// @match        *://*.stclairtoday.com/*
// @match        *://*.stjoebentonharbor.com/*
// @match        *://*.sturgiscoldwaternews.com/*
// @match        *://*.thumbreporter.com/*
// @match        *://*.tricitysun.com/*
// @match        *://*.upgazette.com/*
// @match        *://*.warrensun.com/*
// @match        *://*.waterfordtoday.com/*
// @match        *://*.wcmichigannews.com/*
// @match        *://*.westernwaynetoday.com/*
// @match        *://*.anokatimes.com/*
// @match        *://*.dakotatimes.com/*
// @match        *://*.easttwincities.com/*
// @match        *://*.mabeltoday.com/*
// @match        *://*.minneapolisreview.com/*
// @match        *://*.minnesotastatewire.com/*
// @match        *://*.mnbusinessdaily.com/*
// @match        *://*.mncatholictribune.com/*
// @match        *://*.ncminnesotanews.com/*
// @match        *://*.northhennepinnews.com/*
// @match        *://*.northramseynews.com/*
// @match        *://*.nwminnesotanews.com/*
// @match        *://*.nwtwincities.com/*
// @match        *://*.scminnesotanews.com/*
// @match        *://*.seminnesotanews.com/*
// @match        *://*.setwincities.com/*
// @match        *://*.southhennepinnews.com/*
// @match        *://*.stcloudsun.com/*
// @match        *://*.stpaulreporter.com/*
// @match        *://*.swminnesotatoday.com/*
// @match        *://*.wcminnesotanews.com/*
// @match        *://*.westtwincities.com/*
// @match        *://*.ecmissnews.com/*
// @match        *://*.gtrtimes.com/*
// @match        *://*.hindstoday.com/*
// @match        *://*.magnoliastatenews.com/*
// @match        *://*.msbusinessdaily.com/*
// @match        *://*.msgulfnews.com/*
// @match        *://*.ncmissnews.com/*
// @match        *://*.nemissnews.com/*
// @match        *://*.nwmissnews.com/*
// @match        *://*.oxfordreporter.com/*
// @match        *://*.pinebelttimes.com/*
// @match        *://*.scmissnews.com/*
// @match        *://*.swmissnews.com/*
// @match        *://*.wcmissnews.com/*
// @match        *://*.almastandard.com/*
// @match        *://*.bpsmoguide.com/*
// @match        *://*.bransontimes.com/*
// @match        *://*.capemonews.com/*
// @match        *://*.centralmissourinews.com/*
// @match        *://*.centralstlnews.com/*
// @match        *://*.clayreporter.com/*
// @match        *://*.columbiamonews.com/*
// @match        *://*.greenhillsreporter.com/*
// @match        *://*.jeffcitynews.com/*
// @match        *://*.jeffcotimes.com/*
// @match        *://*.kcreporter.com/*
// @match        *://*.mobusinessdaily.com/*
// @match        *://*.nekansascitynews.com/*
// @match        *://*.nemissourinews.com/*
// @match        *://*.northstlnews.com/*
// @match        *://*.nwmissouritimes.com/*
// @match        *://*.plattenews.com/*
// @match        *://*.scmissourinews.com/*
// @match        *://*.sekansascitynews.com/*
// @match        *://*.semissourinews.com/*
// @match        *://*.showmestatetimes.com/*
// @match        *://*.southkcnews.com/*
// @match        *://*.southstlnews.com/*
// @match        *://*.springfieldstandard.com/*
// @match        *://*.stcharlestimes.com/*
// @match        *://*.steelvilleguide.com/*
// @match        *://*.stlouisreporter.com/*
// @match        *://*.stlrecord.com/*
// @match        *://*.stlwestnews.com/*
// @match        *://*.swmissouriguide.com/*
// @match        *://*.swmissourinews.com/*
// @match        *://*.wcmissourinews.com/*
// @match        *://*.weststlnews.com/*
// @match        *://*.bigskytimes.com/*
// @match        *://*.centralmontanatimes.com/*
// @match        *://*.glaciercountrynews.com/*
// @match        *://*.mtbusinessdaily.com/*
// @match        *://*.nemontananews.com/*
// @match        *://*.nwmontananews.com/*
// @match        *://*.semontananews.com/*
// @match        *://*.swmontanatimes.com/*
// @match        *://*.yellowstonetimes.com/*
// @match        *://*.auroraneguide.com/*
// @match        *://*.bluehillguide.com/*
// @match        *://*.cornhuskerstatenews.com/*
// @match        *://*.ecnebraskanews.com/*
// @match        *://*.nebraskabusinessdaily.com/*
// @match        *://*.nenebraskanews.com/*
// @match        *://*.nepanhandlenews.com/*
// @match        *://*.northomahatimes.com/*
// @match        *://*.omaharecord.com/*
// @match        *://*.sandhillstoday.com/*
// @match        *://*.scnebraskanews.com/*
// @match        *://*.senebraskanews.com/*
// @match        *://*.southomahatimes.com/*
// @match        *://*.swnebraskaguide.com/*
// @match        *://*.eaglevalleytimes.com/*
// @match        *://*.lasvegasrecord.com/*
// @match        *://*.moapavalleyguide.com/*
// @match        *://*.northnevadanews.com/*
// @match        *://*.northvegastimes.com/*
// @match        *://*.nvbusinessdaily.com/*
// @match        *://*.nwclarknews.com/*
// @match        *://*.renoreporter.com/*
// @match        *://*.sevegasnews.com/*
// @match        *://*.silverstatetimes.com/*
// @match        *://*.swvegasnews.com/*
// @match        *://*.washoenews.com/*
// @match        *://*.concordledger.com/*
// @match        *://*.dartmouthtimes.com/*
// @match        *://*.granitestatetimes.com/*
// @match        *://*.hillsboroughsun.com/*
// @match        *://*.lakeregionnews.com/*
// @match        *://*.nhbusinessdaily.com/*
// @match        *://*.northcountryreporter.com/*
// @match        *://*.rockinghamtimes.com/*
// @match        *://*.straffordnews.com/*
// @match        *://*.swnewhampshirenews.com/*
// @match        *://*.atlanticcotimes.com/*
// @match        *://*.burlingtonreview.com/*
// @match        *://*.gardenstatetimes.com/*
// @match        *://*.gloucestertoday.com/*
// @match        *://*.hudsontoday.com/*
// @match        *://*.mercertimes.com/*
// @match        *://*.monmouthtimes.com/*
// @match        *://*.morrisleader.com/*
// @match        *://*.nebergennews.com/*
// @match        *://*.newarkreporter.com/*
// @match        *://*.njbusinessdaily.com/*
// @match        *://*.northessexnews.com/*
// @match        *://*.northmiddlesextimes.com/*
// @match        *://*.nwbergennews.com/*
// @match        *://*.nwjerseynews.com/*
// @match        *://*.oceancountyleader.com/*
// @match        *://*.passiacnews.com/*
// @match        *://*.somersettimes.com/*
// @match        *://*.southbergennews.com/*
// @match        *://*.southjerseysun.com/*
// @match        *://*.southmiddlesextimes.com/*
// @match        *://*.unioncountyreview.com/*
// @match        *://*.westessexnews.com/*
// @match        *://*.abqtimes.com/*
// @match        *://*.eastnewmexiconews.com/*
// @match        *://*.enchantmentstatenews.com/*
// @match        *://*.nenewmexiconews.com/*
// @match        *://*.nmbusinessdaily.com/*
// @match        *://*.nwnewmexiconews.com/*
// @match        *://*.sandovalnews.com/*
// @match        *://*.santafestandard.com/*
// @match        *://*.southabqnews.com/*
// @match        *://*.swnewmexiconews.com/*
// @match        *://*.wcnewmexiconews.com/*
// @match        *://*.buffaloledger.com/*
// @match        *://*.capitaldistricttimes.com/*
// @match        *://*.easthudvalleynews.com/*
// @match        *://*.empirestatetoday.com/*
// @match        *://*.fingerlakestoday.com/*
// @match        *://*.hancocknyguide.com/*
// @match        *://*.mohawkvalleytimes.com/*
// @match        *://*.monroenynews.com/*
// @match        *://*.nassaustandard.com/*
// @match        *://*.nenewyorktoday.com/*
// @match        *://*.niagaraleader.com/*
// @match        *://*.northcountryleader.com/*
// @match        *://*.nybusinessdaily.com/*
// @match        *://*.nycgazette.com/*
// @match        *://*.oneidatimes.com/*
// @match        *://*.rochesterreporter.com/*
// @match        *://*.rocklandreporter.com/*
// @match        *://*.saratogastandard.com/*
// @match        *://*.scnewyorknews.com/*
// @match        *://*.statenislandreporter.com/*
// @match        *://*.suffolkreporter.com/*
// @match        *://*.syracusesun.com/*
// @match        *://*.westchesterreporter.com/*
// @match        *://*.westhudvalleynews.com/*
// @match        *://*.westnynews.com/*
// @match        *://*.ashevillereporter.com/*
// @match        *://*.burlingtonreporter.com/*
// @match        *://*.cabarrustoday.com/*
// @match        *://*.chapelhillreview.com/*
// @match        *://*.durhamreporter.com/*
// @match        *://*.eastlakenormannews.com/*
// @match        *://*.eastwaketimes.com/*
// @match        *://*.ecnorthcarolinanews.com/*
// @match        *://*.fayettevilletoday.com/*
// @match        *://*.foothillsreview.com/*
// @match        *://*.gastoniatimes.com/*
// @match        *://*.greensbororeporter.com/*
// @match        *://*.greenvillereporter.com/*
// @match        *://*.hickorysun.com/*
// @match        *://*.highcountrytimes.com/*
// @match        *://*.ibxnews.com/*
// @match        *://*.johnstonreporter.com/*
// @match        *://*.nantahalanews.com/*
// @match        *://*.ncbusinessdaily.com/*
// @match        *://*.ncncnews.com/*
// @match        *://*.ncunionnews.com/*
// @match        *://*.nepiedmontnews.com/*
// @match        *://*.northcharlottetoday.com/*
// @match        *://*.northguilfordnews.com/*
// @match        *://*.northiredellnews.com/*
// @match        *://*.northmecklenburgnews.com/*
// @match        *://*.northraleightoday.com/*
// @match        *://*.northtrianglenews.com/*
// @match        *://*.northwakenews.com/*
// @match        *://*.oldnorthnews.com/*
// @match        *://*.onslownews.com/*
// @match        *://*.outerbankstimes.com/*
// @match        *://*.pinehursttoday.com/*
// @match        *://*.randolphcountynews.com/*
// @match        *://*.rockymounttoday.com/*
// @match        *://*.rowannews.com/*
// @match        *://*.senorthcarolinanews.com/*
// @match        *://*.southashevillenews.com/*
// @match        *://*.southcharlottetoday.com/*
// @match        *://*.southguilfordnews.com/*
// @match        *://*.southmecklenburgnews.com/*
// @match        *://*.southncnews.com/*
// @match        *://*.southraleighnews.com/*
// @match        *://*.southtrianglenews.com/*
// @match        *://*.southwinstonsalemnews.com/*
// @match        *://*.westlakenormannews.com/*
// @match        *://*.westwakenews.com/*
// @match        *://*.winstonsalemtimes.com/*
// @match        *://*.yadkinvalleynews.com/*
// @match        *://*.centralndnews.com/*
// @match        *://*.fargostandard.com/*
// @match        *://*.ndbusinessdaily.com/*
// @match        *://*.ndnorthnews.com/*
// @match        *://*.nenorthdakotanews.com/*
// @match        *://*.peacegardennews.com/*
// @match        *://*.westernndnews.com/*
// @match        *://*.akronreporter.com/*
// @match        *://*.buckeyereporter.com/*
// @match        *://*.butlercountytoday.com/*
// @match        *://*.cantonreporter.com/*
// @match        *://*.centralohiotoday.com/*
// @match        *://*.cincyreporter.com/*
// @match        *://*.clermonttimes.com/*
// @match        *://*.clevelandreporter.com/*
// @match        *://*.daytonreporter.com/*
// @match        *://*.delcoreview.com/*
// @match        *://*.eastclevelandnews.com/*
// @match        *://*.eaststarknews.com/*
// @match        *://*.ecohionews.com/*
// @match        *://*.fairfieldreporter.com/*
// @match        *://*.findlaytimes.com/*
// @match        *://*.greenecotimes.com/*
// @match        *://*.lakecountytimes.com/*
// @match        *://*.lickingtoday.com/*
// @match        *://*.limareporter.com/*
// @match        *://*.loraintimes.com/*
// @match        *://*.mansfieldtimes.com/*
// @match        *://*.marionmorrowtimes.com/*
// @match        *://*.medinatoday.com/*
// @match        *://*.nefranklinnews.com/*
// @match        *://*.neohiotimes.com/*
// @match        *://*.northcincynews.com/*
// @match        *://*.northcolumbusnews.com/*
// @match        *://*.northdaytonnews.com/*
// @match        *://*.northsummitnews.com/*
// @match        *://*.nwfranklinnews.com/*
// @match        *://*.nwohiotimes.com/*
// @match        *://*.ohbusinessdaily.com/*
// @match        *://*.portagetimes.com/*
// @match        *://*.seohiotimes.com/*
// @match        *://*.southcolumbusnews.com/*
// @match        *://*.southcuyahoganews.com/*
// @match        *://*.southdaytonnews.com/*
// @match        *://*.southfranklinnews.com/*
// @match        *://*.southohionews.com/*
// @match        *://*.southsummitnews.com/*
// @match        *://*.toledoreporter.com/*
// @match        *://*.triconews.com/*
// @match        *://*.trumballnews.com/*
// @match        *://*.tuscarawasnews.com/*
// @match        *://*.vacationlandtimes.com/*
// @match        *://*.warrenclintonnews.com/*
// @match        *://*.waynecountytoday.com/*
// @match        *://*.westclevelandnews.com/*
// @match        *://*.westhamiltonnews.com/*
// @match        *://*.westlucasnews.com/*
// @match        *://*.weststarknews.com/*
// @match        *://*.youngstowntimes.com/*
// @match        *://*.beggsguide.com/*
// @match        *://*.bixbyguide.com/*
// @match        *://*.canadianvalleyguide.com/*
// @match        *://*.eastokcnews.com/*
// @match        *://*.ecoklahomanews.com/*
// @match        *://*.jayokguide.com/*
// @match        *://*.ncoklahomanews.com/*
// @match        *://*.neoklahomanews.com/*
// @match        *://*.northokcnews.com/*
// @match        *://*.northtulsatoday.com/*
// @match        *://*.nwoklahomanews.com/*
// @match        *://*.okbusinessdaily.com/*
// @match        *://*.okcstandard.com/*
// @match        *://*.scoklahomanews.com/*
// @match        *://*.seoklahomanews.com/*
// @match        *://*.soonerstatenews.com/*
// @match        *://*.southokcnews.com/*
// @match        *://*.southtulsatoday.com/*
// @match        *://*.swoklahomanews.com/*
// @match        *://*.tulsastandard.com/*
// @match        *://*.vallianttoday.com/*
// @match        *://*.beaverstatenews.com/*
// @match        *://*.centraloregontimes.com/*
// @match        *://*.eastoregonnews.com/*
// @match        *://*.eastpdxtoday.com/*
// @match        *://*.laneconews.com/*
// @match        *://*.midcoasttimes.com/*
// @match        *://*.midvalleyreporter.com/*
// @match        *://*.nehalemguide.com/*
// @match        *://*.northcoasttoday.com/*
// @match        *://*.orbusinessdaily.com/*
// @match        *://*.portlandcourant.com/*
// @match        *://*.southcoasttimes.com/*
// @match        *://*.southoregonnews.com/*
// @match        *://*.westpdxtoday.com/*
// @match        *://*.directech.co/*
// @match        *://*.freedommedianetwork.com/*
// @match        *://*.hansondirectory.com/*
// @match        *://*.lgis.co/*
// @match        *://*.metricmedianews.com/*
// @match        *://*.metrobusinessnetwork.com/*
// @match        *://*.therecordinc.com/*
// @match        *://*.altoonatimes.com/*
// @match        *://*.beaverconews.com/*
// @match        *://*.berksconews.com/*
// @match        *://*.butlerconews.com/*
// @match        *://*.cambriatimes.com/*
// @match        *://*.centralbuckstoday.com/*
// @match        *://*.centralchestertoday.com/*
// @match        *://*.centralpanews.com/*
// @match        *://*.coalregionnews.com/*
// @match        *://*.crawfordtimes.com/*
// @match        *://*.cumberlandvalleynews.com/*
// @match        *://*.dauphinnews.com/*
// @match        *://*.eastmonttimes.com/*
// @match        *://*.eriecotimes.com/*
// @match        *://*.happyvalleytimes.com/*
// @match        *://*.keystonebusinessnews.com/*
// @match        *://*.keystonetoday.com/*
// @match        *://*.laurelhighlandstoday.com/*
// @match        *://*.lawrencetimes.com/*
// @match        *://*.lebanonpanews.com/*
// @match        *://*.lehightimes.com/*
// @match        *://*.lowerbuckstoday.com/*
// @match        *://*.luzernetimes.com/*
// @match        *://*.lycomingnews.com/*
// @match        *://*.monroeconews.com/*
// @match        *://*.ncpatimes.com/*
// @match        *://*.northalleghenynews.com/*
// @match        *://*.northchestertoday.com/*
// @match        *://*.northdelconews.com/*
// @match        *://*.northerntiernews.com/*
// @match        *://*.northhamptonnews.com/*
// @match        *://*.northlancasternews.com/*
// @match        *://*.northpocononews.com/*
// @match        *://*.nwpanews.com/*
// @match        *://*.palmertonguide.com/*
// @match        *://*.pennrecord.com/*
// @match        *://*.phillyleader.com/*
// @match        *://*.pittreview.com/*
// @match        *://*.scpanews.com/*
// @match        *://*.scrantonreporter.com/*
// @match        *://*.sealleghenynews.com/*
// @match        *://*.shenangovalleynews.com/*
// @match        *://*.southchestertoday.com/*
// @match        *://*.southdelconews.com/*
// @match        *://*.southlancasternews.com/*
// @match        *://*.swalleghenynews.com/*
// @match        *://*.swpanews.com/*
// @match        *://*.upperbuckstoday.com/*
// @match        *://*.wcpanews.com/*
// @match        *://*.westmonttimes.com/*
// @match        *://*.westmorelandreview.com/*
// @match        *://*.yorkconews.com/*
// @match        *://*.manilabusinessdaily.com/*
// @match        *://*.kentcotimes.com/*
// @match        *://*.oceanstatetoday.com/*
// @match        *://*.providencereporter.com/*
// @match        *://*.ribusinessdaily.com/*
// @match        *://*.southcotimes.com/*
// @match        *://*.guatemalabusinessdaily.com/*
// @match        *://*.latinbusinessdaily.com/*
// @match        *://*.aikentimes.com/*
// @match        *://*.berkeleyleader.com/*
// @match        *://*.charlestonreporter.com/*
// @match        *://*.columbiastandard.com/*
// @match        *://*.dorchestertoday.com/*
// @match        *://*.greenvilleleader.com/*
// @match        *://*.hiltonheadreporter.com/*
// @match        *://*.lowerwestscnews.com/*
// @match        *://*.myrtlebeachleader.com/*
// @match        *://*.ncsctimes.com/*
// @match        *://*.palmettobusinessdaily.com/*
// @match        *://*.palmettostatenews.com/*
// @match        *://*.peedeenews.com/*
// @match        *://*.scmidlandnews.com/*
// @match        *://*.spartanburgreporter.com/*
// @match        *://*.upperwestscnews.com/*
// @match        *://*.upstatescnews.com/*
// @match        *://*.bisonguide.com/*
// @match        *://*.centralsdnews.com/*
// @match        *://*.nesdnews.com/*
// @match        *://*.rushmorestatenews.com/*
// @match        *://*.sdbusinessdaily.com/*
// @match        *://*.sesdnews.com/*
// @match        *://*.siouxempiretoday.com/*
// @match        *://*.westernsdnews.com/*
// @match        *://*.mchenrytimes.com/*
// @match        *://*.westlooptoday.com/*
// @match        *://*.clarksvilletimes.com/*
// @match        *://*.hamiltonreporter.com/*
// @match        *://*.johnsoncitytimes.com/*
// @match        *://*.kingsportreporter.com/*
// @match        *://*.knoxtimes.com/*
// @match        *://*.memphisstandard.com/*
// @match        *://*.morristowntimes.com/*
// @match        *://*.nashvillestandard.com/*
// @match        *://*.nctennnews.com/*
// @match        *://*.nenashvillenews.com/*
// @match        *://*.northknoxnews.com/*
// @match        *://*.nwtennnews.com/*
// @match        *://*.rutherfordtimes.com/*
// @match        *://*.sctennnews.com/*
// @match        *://*.setennnews.com/*
// @match        *://*.shelbyreporter.com/*
// @match        *://*.smokymountaintoday.com/*
// @match        *://*.southcumberlandnews.com/*
// @match        *://*.southknoxnews.com/*
// @match        *://*.swtennnews.com/*
// @match        *://*.tnbusinessdaily.com/*
// @match        *://*.uppercumberlandtimes.com/*
// @match        *://*.volunteerstatenews.com/*
// @match        *://*.williamsonnews.com/*
// @match        *://*.abilenetimes.com/*
// @match        *://*.amarillogazette.com/*
// @match        *://*.austintxnews.com/*
// @match        *://*.centraltxnews.com/*
// @match        *://*.centroplexnews.com/*
// @match        *://*.coldspringguide.com/*
// @match        *://*.colemancountyguide.com/*
// @match        *://*.collintimes.com/*
// @match        *://*.coloradovalleyguide.com/*
// @match        *://*.conchovalleynews.com/*
// @match        *://*.corpuschristisun.com/*
// @match        *://*.dallascitywire.com/*
// @match        *://*.eastdfwnews.com/*
// @match        *://*.easthoustonnews.com/*
// @match        *://*.eastrgvnews.com/*
// @match        *://*.ectexasnews.com/*
// @match        *://*.elpasostandard.com/*
// @match        *://*.farwesttxnews.com/*
// @match        *://*.fiveareaguide.com/*
// @match        *://*.forestcountrynews.com/*
// @match        *://*.ftworthtimes.com/*
// @match        *://*.graysontimes.com/*
// @match        *://*.hillcountrychronicle.com/*
// @match        *://*.houstonrepublic.com/*
// @match        *://*.industrytxguide.com/*
// @match        *://*.jacksonreporter.com/*
// @match        *://*.laredotimes.com/*
// @match        *://*.lonestarstandard.com/*
// @match        *://*.longviewtimes.com/*
// @match        *://*.lubbocktimes.com/*
// @match        *://*.midcitytimes.com/*
// @match        *://*.midlandtimes.com/*
// @match        *://*.mtenterprisetoday.com/*
// @match        *://*.nedallasnews.com/*
// @match        *://*.netarrantnews.com/*
// @match        *://*.nortextimes.com/*
// @match        *://*.northaustinnews.com/*
// @match        *://*.northcoastalnews.com/*
// @match        *://*.northhoustonnews.com/*
// @match        *://*.northsanantonionews.com/*
// @match        *://*.northtexasreview.com/*
// @match        *://*.northtxnews.com/*
// @match        *://*.nwhoustonnews.com/*
// @match        *://*.panhandletimes.com/*
// @match        *://*.petroplexnews.com/*
// @match        *://*.pokalambroguide.com/*
// @match        *://*.rivieratxguide.com/*
// @match        *://*.sacorridornews.com/*
// @match        *://*.sanantoniostandard.com/*
// @match        *://*.sctexasnews.com/*
// @match        *://*.sedallasnews.com/*
// @match        *://*.sehoustonnews.com/*
// @match        *://*.setexasrecord.com/*
// @match        *://*.setexastimes.com/*
// @match        *://*.southbrazorianews.com/*
// @match        *://*.southdfwnews.com/*
// @match        *://*.southgalvestonnews.com/*
// @match        *://*.southsanantonionews.com/*
// @match        *://*.spurguide.com/*
// @match        *://*.swdallasnews.com/*
// @match        *://*.swhoustonnews.com/*
// @match        *://*.texasbusinesscoalition.com/*
// @match        *://*.txbusinessdaily.com/*
// @match        *://*.tylerreporter.com/*
// @match        *://*.uppereasttx.com/*
// @match        *://*.urbanreform.org/*
// @match        *://*.wacoreporter.com/*
// @match        *://*.waskomreview.com/*
// @match        *://*.wctexasnews.com/*
// @match        *://*.westdfwnews.com/*
// @match        *://*.westhoustonnews.com/*
// @match        *://*.westrgvnews.com/*
// @match        *://*.westtxnews.com/*
// @match        *://*.wintergardentoday.com/*
// @match        *://*.americancatholictribune.com/*
// @match        *://*.americanpharmacynews.com/*
// @match        *://*.americansecuritynews.com/*
// @match        *://*.catholicmasslive.com/*
// @match        *://*.cropprotectionnews.com/*
// @match        *://*.currentsciencedaily.com/*
// @match        *://*.educationdailywire.com/*
// @match        *://*.epnewswire.com/*
// @match        *://*.fdahealthnews.com/*
// @match        *://*.fdareporter.com/*
// @match        *://*.highereducationtribune.com/*
// @match        *://*.hrdailywire.com/*
// @match        *://*.insuranceratereporter.com/*
// @match        *://*.legalnewsline.com/*
// @match        *://*.megadealernews.com/*
// @match        *://*.patientdaily.com/*
// @match        *://*.powernewswire.com/*
// @match        *://*.propertyinsurancewire.com/*
// @match        *://*.theneighborhoodguardian.com/*
// @match        *://*.tinewsdaily.com/*
// @match        *://*.tobacconewswire.com/*
// @match        *://*.wealthmanagementwire.com/*
// @match        *://*.beehivestatenews.com/*
// @match        *://*.centralutahnews.com/*
// @match        *://*.davistimes.com/*
// @match        *://*.eastslcnews.com/*
// @match        *://*.northutahnews.com/*
// @match        *://*.slctimes.com/*
// @match        *://*.southutahnews.com/*
// @match        *://*.utahvalleytimes.com/*
// @match        *://*.utbusinessdaily.com/*
// @match        *://*.wastachnews.com/*
// @match        *://*.webertimes.com/*
// @match        *://*.westslcnews.com/*
// @match        *://*.burlingtonstandard.com/*
// @match        *://*.greenmountaintimes.com/*
// @match        *://*.ncvermontnews.com/*
// @match        *://*.nevermontnews.com/*
// @match        *://*.scvermontnews.com/*
// @match        *://*.southvermontnews.com/*
// @match        *://*.vtbusinessdaily.com/*
// @match        *://*.centralnovanews.com/*
// @match        *://*.centralshenandoahnews.com/*
// @match        *://*.centralvatimes.com/*
// @match        *://*.easternshoretimes.com/*
// @match        *://*.ecvirginianews.com/*
// @match        *://*.fredericksburgleader.com/*
// @match        *://*.gatewayreporter.com/*
// @match        *://*.henricotimes.com/*
// @match        *://*.lynchburgreporter.com/*
// @match        *://*.newrivervalleytimes.com/*
// @match        *://*.northernnecktimes.com/*
// @match        *://*.northfairfaxnews.com/*
// @match        *://*.northrichmondtoday.com/*
// @match        *://*.northshenandoahnews.com/*
// @match        *://*.northtidewaternews.com/*
// @match        *://*.olddominionnews.com/*
// @match        *://*.princewilliamreporter.com/*
// @match        *://*.richmondleader.com/*
// @match        *://*.roanokesun.com/*
// @match        *://*.scvanews.com/*
// @match        *://*.shenandoahvalleynews.com/*
// @match        *://*.southfairfaxnews.com/*
// @match        *://*.southsidevanews.com/*
// @match        *://*.southtidewaternews.com/*
// @match        *://*.swvirginianews.com/*
// @match        *://*.vabusinessdaily.com/*
// @match        *://*.westnovanews.com/*
// @match        *://*.williamsburgsun.com/*
// @match        *://*.eastkingnews.com/*
// @match        *://*.evergreenreporter.com/*
// @match        *://*.kitsapreview.com/*
// @match        *://*.moseslaketoday.com/*
// @match        *://*.newashingtonnews.com/*
// @match        *://*.northkingnews.com/*
// @match        *://*.northsnohomishnews.com/*
// @match        *://*.nwwashingtonnews.com/*
// @match        *://*.olympictimes.com/*
// @match        *://*.piercetoday.com/*
// @match        *://*.seattlecitywire.com/*
// @match        *://*.sewashingtonnews.com/*
// @match        *://*.southkingnews.com/*
// @match        *://*.southsnohomishnews.com/*
// @match        *://*.southsoundtimes.com/*
// @match        *://*.spokanecotimes.com/*
// @match        *://*.spokanestandard.com/*
// @match        *://*.tricitiesreporter.com/*
// @match        *://*.vancouverreporter.com/*
// @match        *://*.wabusinessdaily.com/*
// @match        *://*.waislenews.com/*
// @match        *://*.wenatcheetimes.com/*
// @match        *://*.yakimatimes.com/*
// @match        *://*.dcbusinessdaily.com/*
// @match        *://*.alleghenyhighlandstoday.com/*
// @match        *://*.bluestonenews.com/*
// @match        *://*.charlestonleader.com/*
// @match        *://*.eastpanhandletimes.com/*
// @match        *://*.huntingtontimes.com/*
// @match        *://*.mountainstatetimes.com/*
// @match        *://*.ncwvnews.com/*
// @match        *://*.northpanhandletimes.com/*
// @match        *://*.ohiovalleytimes.com/*
// @match        *://*.southernwvnews.com/*
// @match        *://*.wvbusinessdaily.com/*
// @match        *://*.wvheartlandnews.com/*
// @match        *://*.wvrecord.com/*
// @match        *://*.centralwisconsinnews.com/*
// @match        *://*.chippewavalleytimes.com/*
// @match        *://*.ecwisconsinnews.com/*
// @match        *://*.fondulacnews.com/*
// @match        *://*.foxcitiesnews.com/*
// @match        *://*.greenbayreporter.com/*
// @match        *://*.kenoshareporter.com/*
// @match        *://*.madisonreporter.com/*
// @match        *://*.mkecitywire.com/*
// @match        *://*.mkenorth.com/*
// @match        *://*.mkesouth.com/*
// @match        *://*.ncwisconsinnews.com/*
// @match        *://*.newisconsinnews.com/*
// @match        *://*.northwoodsreporter.com/*
// @match        *://*.ozaukeetimes.com/*
// @match        *://*.racinesun.com/*
// @match        *://*.scwisconsinnews.com/*
// @match        *://*.sowisconsintimes.com/*
// @match        *://*.swwisconsinnews.com/*
// @match        *://*.thesconi.com/*
// @match        *://*.washingtoncotimes.com/*
// @match        *://*.waukeshatimes.com/*
// @match        *://*.wcwisconsinnews.com/*
// @match        *://*.whitewatertimes.com/*
// @match        *://*.wibusinessdaily.com/*
// @match        *://*.wicatholictribune.com/*
// @match        *://*.centralwynews.com/*
// @match        *://*.equalitystatenews.com/*
// @match        *://*.newyomingnews.com/*
// @match        *://*.nwwyomingnews.com/*
// @match        *://*.sewyomingnews.com/*
// @match        *://*.swwyomingnews.com/*
// @match        *://*.wybusinessdaily.com/*
// @grant        none
// ==/UserScript==

window.stop();
document.documentElement.innerHTML="<h1>Error 404: Page Not Found</h1><p>Sorry, but the page you were trying to view does not exist.</p>";
